project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView
from .signup import signup
from todo.views import book_catalogue, main

urlpatterns = (
    [
        path("", main, name="main"),
        path("book_catalogue", book_catalogue, name="book_catalogue"),
        path("home", TemplateView.as_view(template_name="home.html"), name="home"),
        path("login", auth_views.LoginView.as_view(), name="login"),
        path("logout", auth_views.LogoutView.as_view(), name="logout"),
        path("todoadmin/", admin.site.urls),
        path("todo/", include("todo.urls", namespace="todo")),
        path('signup/', signup, name='signup'),
    ]
    # Static media in DEBUG mode:
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

todo/urls.py
from django.conf import settings
from django.urls import path

from todo import views

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    path("illustration_petitions/", views.task_lists, name="task_lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("accepted_petitions/", views.accepted_petitions, name="accepted_petitions"),
    path("users_management/", views.users_management, name="users_management"),
    path("books_management/", views.books_management, name="books_management"),
    path("statistics/<int:book_id>/", views.book_statistics, name="book_statistics"),
    path("books_management/<int:book_id>/edit", views.book_edit, name="book_edit"),
    path("users_management/<str:list_slug>/", views.users_detail, name="users_detail"),
    path("users_management/<str:list_slug>/add", views.add_user, name="add_user"),
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    path("set_firstime_password/<str:uuid>/", views.set_ft_pass, name="set_ft_pass"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path("mine/completed", views.list_detail, {"list_slug": "mine", "view_completed": True}, name="mine_completed"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("book/<int:book_id>/assign", views.book_assign, name="book_assign"),
    path("book/<int:book_id>/<str:format>/download", views.download_book, name="download_book"),
    path("task/<int:task_id>/assign", views.designer_assign, name="designer_assign"),
    path("book/<int:book_id>/publish", views.book_publish, name="book_publish"),
    path("book/<int:book_id>/detail", views.book_detail, name="book_detail"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
    path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
    path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
    path("search/", views.search, name="search"),
    path("categories/<str:category_id>/", views.book_category, name="book_category"),
    path("createsubscription", views.create_subscription, name="create_subscription"),
    path("cancelsubscription", views.cancel_subscription, name="cancel_subscription"),
    path("deactivateuser", views.deactivate_user, name="deactivate_user"),
    path("activateuser", views.activate_user, name="activate_user"),
    path("deactivatebook", views.deactivate_book, name="deactivate_book"),
    path("activatebook", views.activate_book, name="activate_book"),
    path("profile/", views.profile, name="profile"),
    path("changepassword/", views.change_password, name="change_password"),
]

project/forms.py
import unicodedata
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation, get_user_model
from django.utils.translation import gettext_lazy as _

# Based on: https://github.com/django/django/blob/main/django/contrib/auth/forms.py

class EmailField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize('NFKC', super().to_python(value))

    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            'autocapitalize': 'none',
            'autocomplete': 'email',
        }

class UserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    full_name = forms.CharField(
        label=_("Full name"),
        strip=False,
        required=False,
    )
    chief = forms.BooleanField(
        label=_("Chief"),
        required=False,
    )

    class Meta:
        model = get_user_model()
        
        fields = ("email",)
        field_classes = {'email': EmailField}

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

project/templates/base.html
{% load static %}
{% load todo_tags %}
<!doctype html>
<html lang="en">
  <head>
    <link rel="shortcut icon" type="image/png" href="{% static '/images/logo_small_icon_only.png' %}"/>
    <link rel="icon" type="image/png" href="{% static '/images/logo_small_icon_only.png' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/bebas" type="text/css"/>

    <title>Editorial Bookiernes, S.A.</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href="/static/css/sticky-footer-navbar.css" rel="stylesheet">

    {# Additional CSS or html head data inserted by templates here. #}
    {% block extrahead %}{% endblock extrahead %}

    <style>
      body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
      body {font-size: 16px;}
      .w3-xxxlarge {font-family: 'BebasNeueRegular'; font-size: 60px!important;}
      .w3-xlarge { font-family: 'BebasNeueRegular'; font-size: 30px!important;}
      .w3-jumbo > b { font-family: 'BebasNeueRegular'; font-size: 80px!important;}
      img {margin-bottom: -8px;}
      .mySlides {display: none;}
    </style>
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a id="image-logo" class="navbar-brand" href="/"><img src="{% static '/images/logo_small.png' %}" height="45px"/></a>
        <!--<a class="navbar-brand" href="/">BOOKIERNES</a>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            {% if user|is_staff %}
              {% if user|can_see_not_accepted %} 
              <li id="peticiones" class="nav-item"><a href="{% url 'todo:lists' %}" class="nav-link">Peticiones de edición</a></li>
              {% endif %}
              {% if user|is_graphic_designer %} 
                {% if user|is_chief_designer %}
                <li id="peticiones" class="nav-item"><a href="{% url 'todo:task_lists' %}" class="nav-link">Peticiones de diseño</a></li>
                {% endif %}
                <li id="tareas-personales" class="nav-item"><a href="{% url 'todo:mine' %}" class="nav-link">Tareas personales</a></li>
              {% else %}
                {% if user|is_management %}
                <li id="management-users" class="nav-item"><a href="{% url 'todo:users_management' %}" class="nav-link">Gestión de usuarios</a></li>
                <li id="management-books" class="nav-item"><a href="{% url 'todo:books_management' %}" class="nav-link">Gestión de libros</a></li>
                {% else %}
                <li id="peticiones-acc" class="nav-item"><a href="{% url 'todo:accepted_petitions' %}" class="nav-link">Libros en edición</a></li>
                {% endif %}
              {% endif %}
            {% endif %}
            {% if user|is_writer %} 
              <li id="peticiones" class="nav-item"><a href="{% url 'todo:lists' %}" class="nav-link">Peticiones de edición</a></li>
              <li id="tareas-personales" class="nav-item"><a href="{% url 'todo:mine' %}" class="nav-link">Tareas personales</a></li>
              <li id="tareas-personales" class="nav-item"><a href="{% url 'todo:external_add' %}" class="nav-link">Envíanos una nueva obra</a></li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li style="display: flex;" class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Cerrar sesión</a>&nbsp&nbsp<a href="{% url 'todo:profile' %}"><img src="/static/images/avatar.png" style="height: 40px;" class="rounded-circle"></a></li>
            {% else %}
              <li style="padding: 10px" button class="w3-btn w3-round w3-medium"><a href="{% url 'login' %}" class="nav-link">Iniciar sesión</a></button></li>
              <li style="padding: 10px" button class="btn btn-outline-secondary btn-md"><a href="{% url 'signup' %}" class="nav-link"><b>¿Quieres leer? Regístrate</b></a></button></li>&nbsp
              <li style="padding: 10px" button class="btn btn-outline-secondary btn-md"><a href="{% url 'todo:external_add' %}" class="nav-link"><b>¿Eres escritor? Envíanos tu obra</b></a></button></li>
            {% endif %}
          </ul>

          <!--
          {% if user.is_authenticated %}
      		  <form class="form-inline mt-2 mt-md-0" action="{% url 'todo:search' %}" method="get" placeholder="Search" aria-label="Search">
              <input type="text" name="q" value="" class="form-control mr-sm-2" id="q">
              <input type="submit" value="Buscar tareas" class="btn btn-outline-success my-2 my-sm-0">
            </form>
          {% endif %}
          -->

        </div>
      </nav>
      <br><br><br><br>
      
      {% if user|is_staff %}
      {% else %}
        {% if request.get_full_path == "/" or request.get_full_path == "/home" or "categories" in request.path or "search" in request.path or request.get_full_path == "/book_catalogue" or "/todo/book" in request.path %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white" style="width: 100%; text-align: center; margin-top: 75px;" id="submenu">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item" style="margin-top: 3.5%;">
                  {% if request.get_full_path == "/book_catalogue" %}
                    <a href="/" class="w3-bar-item w3-button w3-mobile w3-dark-grey">INICIO</a>
                  {% else %}
                    <a href="/" class="w3-bar-item w3-button w3-mobile w3-light-grey">INICIO</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  {% if request.get_full_path == "/home" %}
                    <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-mobile w3-dark-grey" style="margin-left: 8%; margin-top: 7.5%;">¿QUÉ ES BOOKIERNES?</a>
                  {% else %}
                  <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-mobile w3-light-grey" style="margin-left: 8%; margin-top: 7.5%;">¿QUÉ ES BOOKIERNES?</a>
                  {% endif %}
                </li>
                <div class="w3-dropdown-hover w3-mobile" style="margin-left: 7.5%; margin-top: 3.5%;">
                  {% if "categories" in request.path %}
                    <button class="w3-button w3-dark-grey">CATEGORIAS <i class="fa fa-caret-down"></i></button>
                  {% else %}
                  <button class="w3-button w3-light-grey">CATEGORIAS <i class="fa fa-caret-down"></i></button>
                  {% endif %}
                  <div class="w3-dropdown-content w3-bar-block w3-dark-grey">
                    <a href="{% url 'todo:book_category' 'Todos' %}" class="w3-bar-item w3-button w3-mobile">TODOS LOS LIBROS</a>
                    {% for cat in None|get_book_categories %}
                      <a href="{% url 'todo:book_category' cat %}" class="w3-bar-item w3-button w3-mobile">{{cat}}</a>
                    {% endfor %}
                  </div>
              </ul>
              <form method="get" action="{% url 'todo:search'  %}" class="d-flex" style="margin-left: 35%; margin-top: 1.5%;">
                <input class="form-control me-2" name="w" type="text" placeholder="Título o autor del libro..." aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar libro</button>
              </form>
            </div>
          </div>
        </nav>
      </header>
      {% endif %}
    {% endif %}


    <!-- Begin page content -->
    <main role="main" class="container" style="min-height: calc(100vh - 170px);">

      {% if messages %}
        {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
      {% endif %}

      <p>{{ form.non_field_errors }}</p>

      {% block content %}{% endblock %}
    </main>

    <footer>
      <div class="w3-container w3-white">
        <br>
        <span class="text-muted">
          <div class="row" style="max-width: 100%;">
            <div style="margin-left: 7%" class="col-md-2">
                <a id="logo-icon-small" href="/"><img src="{% static '/images/logo_small_icon_only.png' %}" height="40px"/></a>
                <h3 style="font-family: 'BebasNeueRegular'; color: black; margin-left: 10px;">BOOKIERNES S.A.</h3>
                <p style="margin-left: 10%; white-space: nowrap;font-size: 10px;">Copyright © 2021 BOOKIERNES S.A. Todos los derechos reservados</p>
            </div>
            <div class="col-md-2">
                <a href="/">Aviso Legal</a>
            </div>
            <div class="col-md-2">
                <a href="/">Política de privacidad</a>
            </div>
            <div class="col-md-2">
                <a href="/">Política de cookies</a>
            </div>
            <div class="col-md-2">
              <p style="text-align: left;">
                <b>CONTÁCTANOS</b><br>
                <i style="margin-top: 10px;" class="fa fa-envelope"> info@bookiernes.com</i>
                <i style="margin-top: 10px;" class="fa fa-phone"> (+34) 6XX XX XX XX</i>
              </p>
          </div>
        </div>
      </div>
    </footer> 

    
    <!-- jQuery and Bootstrap core JS, plus Popper -->
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block extra_js %}{% endblock extra_js %}

  </body>
</html>

project/templates/home.html
{% extends "base.html" %} {% block title %}django-todo{% endblock %}

{% block content %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Header -->
<header class="w3-display-container w3-center">
  <button class="w3-button w3-block w3-green w3-hide-large w3-hide-medium" onclick="document.getElementById('download').style.display='block'">Download <i class="fa fa-android"></i> <i class="fa fa-apple"></i> <i class="fa fa-windows"></i></button>
  <div class="mySlides w3-animate-opacity">
    <img class="w3-image" src="/static/images/home.jpg" alt="Image 1" style="min-width:500px" width="1500" height="1000">
    <div class="w3-display-left w3-padding w3-hide-small" style="width:35%">
      <div class="w3-black w3-opacity w3-hover-opacity-off w3-padding-large w3-round-large">
        <h1 class="w3-xlarge">EDITORIAL BOOKIERNES S.A.</h1>
        <hr class="w3-opacity">
        <p>Edita, Publica y Lee tus libros favortitos</p>
      </div>
    </div>
  </div>
  <div class="w3-button w3-block w3-black w3-hide-large w3-hide-medium"></div>
    {% if user.is_authenticated %}
    {% else %}
    <a class="w3-button w3-black w3-display-right w3-margin-right w3-round w3-hide-small w3-hover-light-grey" href="{% url 'login' %}">ACCEDE <i class="fa fa-angle-right"></i></a>
    {% endif %}
  </div>
</header>

<!-- Info Section -->
<div class="w3-padding-64 w3-white">
  <div class="w3-row-padding">
    <div class="w3-col l8 m6">
      <h1 class="w3-jumbo"><b>BOOKIERNES</b></h1>
      <h1 class="w3-xxxlarge w3-text-green"><b>¿Qué puedes hacer?</b></h1>
      <p style="text-align: justify;"><span class="w3-xlarge">Edita tus libros.</span> Cuenta con profesionales 
        a la hora de convertir tu manuscrito en un libro terminado y listo para venderse al público. Si quieres lo mejor para tu 
        libro, ponlo en manos expertas. Es una cuestión de respeto, hacia tu contenido y hacia tus lectores, 
        que el libro vea la luz con la mejor calidad. Los lectores de contenidos independientes son cada vez
        más exigentes y los libros con aspecto poco cuidado, por buenos que sean, tendrán menos posibilidades
        de triunfar. Por lo tanto, evita editar un libro sin asesoría profesional.</p>
      <p style="text-align: justify;"><span class="w3-xlarge">Publica tus libros.</span> ¿Te gustaría que tu libro electrónico pudiera llegar
        a millones de lectores de alrededor del planeta? Nuestro servicio de publicación de libros te ofrece 
        la posibilidad de publicar tu libro digital una vez editado y maquetado a nuestra página web, visible
        para cualquier lector de nuestra comunidad.</p>
      <p style="text-align: justify;"><span class="w3-xlarge">Lee libros digitales.</span> Bookiernes también proporciona una librería digital
        para todos los apasionados de la lectura.</p>
    </div>
    <div class="w3-col l4 m6">
      <br>
      <br>
      <br>
      <img src="/static/images/home_little3.jpg" class="w3-image w3-right w3-hide-small" width="315" height="451">
    </div>
    <div class="w3-col l4 m6">
      <br>
      <img src="/static/images/home_little2.jpg" class="w3-image w3-right w3-hide-small" width="335" height="471">
    </div>
  </div>
</div>

<!-- About us Section -->
<div class="w3-padding-64 w3-light-grey">
  <div class="w3-row-padding">
    <div class="w3-col l4 m6">
      <br>
      <br>
      <br>
      <img class="w3-image w3-round-large w3-hide-small w3-grayscale" src="/static/images/home_little1.jpg" alt="App" width="335" height="471">
    </div>
    <div class="w3-col l8 m6">
      <h1 class="w3-jumbo"><b>About us</b></h1>
      <h1 class="w3-xxxlarge w3-text-red"><b>¿Quiénes somos?</b></h1>
      <p style="text-align: justify;"><span class="w3-medium">En la empresa Bookiernes S.A. somos responsables de la editorial “Bookiernes”. Nuestra actividad 
        se centra en la edición y suministro de libros digitales. 
        A lo largo de nuestro camino hemos descubierto miles de editores, maquetadores y autores que lideran 
        sus proyectos editoriales. Personas que han apostado por Bookiernes a la hora de editar, ilustrar,
        maquetar y publicar un libro y que actualmente gestionan de nuestra mano los derechos editoriales 
        así como los beneficios de sus obras.</p>
    </div>
  </div>
</div>

<!-- Functionalities Section -->
<div class="w3-container w3-padding-64 w3-dark-grey w3-center">
  <h1 class="w3-jumbo"><b>Funcionalidades</b></h1>
  <p>Justamente lo que estabas buscando.</p>

  <div class="w3-row" style="margin-top:64px">
    <div class="w3-col s3">
      <i class="fa fa-bolt w3-text-orange w3-jumbo"></i>
      <p>Presentación de libros rápida</p>
    </div>

    <div class="w3-col s3">
      <i class="fa fa-user w3-text-sand w3-jumbo"></i>
      <p>Asignación de un editor personal</p>
    </div>

    <div class="w3-col s3">
      <i class="fa fa-image w3-text-pink w3-jumbo"></i>
      <p>Ilustración y maquetación</p>
    </div>

    <div class="w3-col s3">
      <i class="fa fa-hdd-o w3-text-cyan w3-jumbo"></i>
      <p>Sin pérdidas de datos</p>
    </div>

    <div class="w3-col s3">
      <i class="fa fa-cloud w3-text-blue w3-jumbo"></i>
      <p>Publicación</p>
    </div>

    <div class="w3-col s3">
      <i class="fa fa-globe w3-text-amber w3-jumbo"></i>
      <p>Lectores de todo el mundo</p>
    </div>
    
  </div>
</div>


<script>
// Slideshow
var slideIndex = 1;
showDivs(slideIndex);

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>

{% endblock %}

project/templates/submenu.html
{% extends "base.html" %} 
{% block title %}submenu{% endblock %}

{% block content %}


<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><body>

<a href="init" class="w3-bar-item w3-button w3-mobile w3-dark-grey">INICIO</a>
<a href="home" class="w3-bar-item w3-button w3-mobile w3-light-grey">¿QUÉ ES BOOKIERNES?</a>
<div class="w3-dropdown-hover w3-mobile">
<button class="w3-button">CATEGORIAS <i class="fa fa-caret-down"></i></button>
    <div class="w3-dropdown-content w3-bar-block w3-dark-grey">
        <a href="#" class="w3-bar-item w3-button w3-mobile">ROMANCE</a>
        <a href="#" class="w3-bar-item w3-button w3-mobile">AVENTURAS</a>
        <a href="#" class="w3-bar-item w3-button w3-mobile">TERROR</a>
    </div>
</div>
<a href="#" style="margin-left: 36%;">¿Nuevo por aquí? SUSCRÍBETE</a>

{% endblock %}