project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView
from .signup import signup
from todo.views import book_catalogue, main

urlpatterns = (
    [
        path("", main, name="main"),
        path("book_catalogue", book_catalogue, name="book_catalogue"),
        path("home", TemplateView.as_view(template_name="home.html"), name="home"),
        path("login", auth_views.LoginView.as_view(), name="login"),
        path("logout", auth_views.LogoutView.as_view(), name="logout"),
        path("todoadmin/", admin.site.urls),
        path("todo/", include("todo.urls", namespace="todo")),
        path('signup/', signup, name='signup'),
    ]
    # Static media in DEBUG mode:
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

todo/urls.py
from django.conf import settings
from django.urls import path

from todo import views

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    path("illustration_petitions/", views.task_lists, name="task_lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("accepted_petitions/", views.accepted_petitions, name="accepted_petitions"),
    path("users_management/", views.users_management, name="users_management"),
    path("books_management/", views.books_management, name="books_management"),
    path("statistics/<int:book_id>/", views.book_statistics, name="book_statistics"),
    path("books_management/<int:book_id>/edit", views.book_edit, name="book_edit"),
    path("users_management/<str:list_slug>/", views.users_detail, name="users_detail"),
    path("users_management/<str:list_slug>/add", views.add_user, name="add_user"),
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    path("set_firstime_password/<str:uuid>/", views.set_ft_pass, name="set_ft_pass"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path("mine/completed", views.list_detail, {"list_slug": "mine", "view_completed": True}, name="mine_completed"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("book/<int:book_id>/assign", views.book_assign, name="book_assign"),
    path("book/<int:book_id>/<str:format>/download", views.download_book, name="download_book"),
    path("task/<int:task_id>/assign", views.designer_assign, name="designer_assign"),
    path("book/<int:book_id>/publish", views.book_publish, name="book_publish"),
    path("book/<int:book_id>/detail", views.book_detail, name="book_detail"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
    path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
    path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
    path("search/", views.search, name="search"),
    path("categories/<str:category_id>/", views.book_category, name="book_category"),
    path("createsubscription", views.create_subscription, name="create_subscription"),
    path("cancelsubscription", views.cancel_subscription, name="cancel_subscription"),
    path("deactivateuser", views.deactivate_user, name="deactivate_user"),
    path("activateuser", views.activate_user, name="activate_user"),
    path("deactivatebook", views.deactivate_book, name="deactivate_book"),
    path("activatebook", views.activate_book, name="activate_book"),
    path("profile/", views.profile, name="profile"),
    path("changepassword/", views.change_password, name="change_password"),
]

todo/models.py
from __future__ import barry_as_FLUFL, unicode_literals

import datetime
import os
import textwrap

from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.auth import models as auth_models
from cuser.models import AbstractCUser
from django.db import DEFAULT_DB_ALIAS, models
from django.db.transaction import Atomic, get_connection
from django.urls import reverse
from django.utils import timezone
from datetime import date
from django import forms
from django.utils.text import slugify

from abc import ABC
import uuid

class LockedAtomicTransaction(Atomic):
    """
    modified from https://stackoverflow.com/a/41831049
    this is needed for safely merging

    Does a atomic transaction, but also locks the entire table for any transactions, for the duration of this
    transaction. Although this is the only way to avoid concurrency issues in certain situations, it should be used with
    caution, since it has impacts on performance, for obvious reasons...
    """

    def __init__(self, *models, using=None, savepoint=None):
        if using is None:
            using = DEFAULT_DB_ALIAS
        super().__init__(using, savepoint)
        self.models = models

    def __enter__(self):
        super(LockedAtomicTransaction, self).__enter__()

        # Make sure not to lock, when sqlite is used, or you'll run into problems while running tests!!!
        if settings.DATABASES[self.using]["ENGINE"] != "django.db.backends.sqlite3":
            cursor = None
            try:
                cursor = get_connection(self.using).cursor()
                for model in self.models:
                    cursor.execute(
                        "LOCK TABLE {table_name}".format(table_name=model._meta.db_table)
                    )
            finally:
                if cursor and not cursor.closed:
                    cursor.close()

# Does this look repetitive to you?
# Then great! It looks repetitive to me too!

# The way Django works, this way of building the models
# is better for form handling.

class UserInfo(models.Model):
    full_name = models.CharField(max_length=150)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE,
        related_name='user_info'
    )
    reset_unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    used_reset = models.BooleanField(default=False)

    def __str__(self):
        return str(self.full_name)

# This should be an ABC, but that interferes
# with the model's metaclass
class UserRole(models.Model):
    def __str__(self):
        return str(self.user.user_info)

class Writer(UserRole):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE
    )


class Editor(UserRole):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE
    )
    chief = models.BooleanField(default=False)

# These classes are not to be used in the first iteration of
# the app. However, modeling them helps us make better design decisions
# and prepare generic code :D

class Designer(UserRole):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE
    )
    chief = models.BooleanField(default=False)

class Management(UserRole):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE
    )

class CreditCardInfo(models.Model):
    card_number = models.PositiveIntegerField(blank=False)
    card_holder = models.TextField(blank=False)
    expiration_date = models.DateField(blank=False)
    card_cvv = models.PositiveIntegerField(blank=False)

class Reader(UserRole):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        null=False,
        on_delete=models.CASCADE
    )
    subscribed = models.BooleanField(default=False)
    credit_card = models.OneToOneField(
        CreditCardInfo,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f'Reader {self.pk}'

class Book(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField(default="", unique=True)
    author = models.ForeignKey(Writer, on_delete=models.RESTRICT, related_name='book_author')
    editor = models.ForeignKey(Editor, null=True, blank=True, on_delete=models.CASCADE, related_name='book_editor')
    # This attribute is techincally redundant:
    # In practice it is a performace improvement and improves legibility
    presentation_date = models.DateField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    description = models.TextField(blank=True)
    # file can bee null for debugging purposes
    file = models.FileField(upload_to="books/attachments", max_length=255, null=True, blank=True)

    TYPE_SCARE = 'S'
    TYPE_ADVENTURE = 'A'
    TYPE_FANTASY = 'F'

    THEMATIC = [
        (TYPE_SCARE, 'Terror'),
        (TYPE_ADVENTURE, 'Aventura'),
        (TYPE_FANTASY, 'Fantasía'),
    ]

    thematic = models.CharField(
        max_length=2,
        choices=THEMATIC,
    )

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Book, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Books"

class PublishedBook(models.Model):
    book = models.OneToOneField(
        Book,
        null=False,
        blank=False,
        related_name="published_book",
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=80)

    publication_date = models.DateField(auto_now_add=True)
    disabled = models.BooleanField(default=False)
    author_text = models.TextField()
    final_version = models.FileField(upload_to="books/attachments", max_length=255, null=True, blank=True)
    final_version_epub = models.FileField(upload_to="books/attachments", max_length=255, null=True, blank=True)
    related_image = models.ImageField(upload_to="books/attachments", null=True, blank=True)

class RecordedDownload(models.Model):
    book = models.ForeignKey(
        Book,
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    download_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      null=False,
      blank=False,
      on_delete=models.CASCADE  
    )
    
    PDF = 'P'
    EPUB = 'E'

    TYPES_OF_DOWNLOAD_CHOICES = [
        (PDF, 'PDF'),
        (EPUB, 'EPUB'),
    ]
    download_type = models.CharField(
        max_length=2,
        choices=TYPES_OF_DOWNLOAD_CHOICES,
        default=PDF,
    )

class Task(models.Model):

    WRITING = 'E'
    ILLUSTRATION = 'I'
    LAYOUT = 'M'
    REVISION = 'R'

    TYPES_OF_TASK_CHOICES = [
        (WRITING, 'Escritura'),
        (ILLUSTRATION, 'Ilustración'),
        (LAYOUT, 'Maquetación'),
        (REVISION, 'Revisión final'),
    ]

    title = models.CharField(max_length=140)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    created_date = models.DateField(auto_now_add=True)
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    notified_due_date = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    task_type = models.CharField(
        max_length=2,
        choices=TYPES_OF_TASK_CHOICES,
        default=WRITING,
    )
    created_by = models.ForeignKey(
        Editor,
        null=True,
        blank=True,
        related_name="todo_created_by",
        on_delete=models.CASCADE,
    )
    assigned_to = models.ForeignKey(
        UserInfo,
        blank=True,
        null=True,
        related_name="todo_assigned_to",
        on_delete=models.CASCADE,
    )
    description = models.TextField(default="")
    priority = models.PositiveIntegerField(blank=True, null=True)

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo:task_detail", kwargs={"task_id": self.id})

    # Auto-set the Task creation / completed date
    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Task, self).save()

    def merge_into(self, merge_target):
        if merge_target.pk == self.pk:
            raise ValueError("can't merge a task with self")

        # lock the comments to avoid concurrent additions of comments after the
        # update request. these comments would be irremediably lost because of
        # the cascade clause
        with LockedAtomicTransaction(Comment):
            Comment.objects.filter(task=self).update(task=merge_target)
            self.delete()

    class Meta:
        ordering = ["priority", "created_date"]


class Comment(models.Model):
    author = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField(default="")

    @property
    def author_text(self):
        return str(self.author)

    @property
    def snippet(self):
        body_snippet = textwrap.shorten(self.body, width=35, placeholder="...")

todo/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.contrib.auth import forms as auth_forms
from django.forms import ModelForm
from todo.models import CreditCardInfo, Task, Book, UserInfo, Editor, Designer, PublishedBook, Reader 


class AddBookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["thematic"].queryset = Book.THEMATIC
        self.fields["thematic"].widget.attrs = {
            "id": "id_thematic",
            "class": "custom-select mb-3",
            "name": "thematic",
        }

    class Meta:
        model = Book
        exclude = ["created_date", "slug", "author", "editor", "completed", "file"]


class AddEditTaskForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["task_type"].queryset = Task.TYPES_OF_TASK_CHOICES
        self.fields["task_type"].widget.attrs = {
            "id": "id_task_type",
            "class": "custom-select mb-3",
            "name": "task_type",
        }
        self.fields["book"].value = kwargs["initial"]["book"].id

    due_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), required=False)
    title = forms.CharField(widget=forms.widgets.TextInput())
    note = forms.CharField(widget=forms.Textarea(), required=False)

    def clean_created_by(self):
        return self.instance.created_by

    class Meta:
        model = Task
        exclude = ["assigned_to", "created_date"]


class AddExternalBookForm(ModelForm):
    class Meta:
        model = UserInfo
        exclude = (
            "user",
        )

class PublishedBookForm(ModelForm):
    class Meta:
        model = PublishedBook
        exclude = (
            "book", "author_text", "disabled"
        )

class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.widgets.TextInput(attrs={"size": 35}))

class AssignForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["editor"].widget.attrs = {
            #"id": "id_thematic",
            "class": "custom-select mb-3",
            #"name": "thematic",
        }
        self.fields["editor"].label = ""

    editor = forms.ModelChoiceField(queryset=Editor.objects.all())

class AssignFormDesigner(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["designer"].widget.attrs = {
            #"id": "id_thematic",
            "class": "custom-select mb-3",
            #"name": "thematic",
        }
        self.fields["designer"].label = ""

    designer = forms.ModelChoiceField(queryset=Designer.objects.all())

class PaymentSubscriptionForm(ModelForm):
    class Meta:
        model = CreditCardInfo
        exclude = []



class profileForm(auth_forms.UserChangeForm):
    class Meta:
        model = UserInfo
        fields = (
            'full_name',
            'user',
            )

todo/views/book_catalogue.py
import datetime
import os

import bleach
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from project import templates

from todo.models import Book, PublishedBook

def book_catalogue(request) -> HttpResponse:
    books = PublishedBook.objects.filter(disabled=False)
    success = True

    context = {
        "success": success,
        "published_books": books,
    }


    return render(request, "todo/main.html", context)

todo/templates/todo/add_task_external.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Presentar libro{% endblock %}

{% block content %}

  <h2>{{ task }}</h2>

  <h3 class="bar-text">¿Quieres publicar tu obra?</h3>
  <p>
    En Bookiernes S.A. nos especializamos en la edición y distribución de calidad. Rellene el siguiente formulario y su libro será revisado por uno de nuestros editores.
    Consulte nuestra <a href="/">Política de privacidad</a>.
  </p>

  {% if form.errors %}
    {% for error in form.errors %}
      <ul class="errorlist">
        <li>
          <strong>The {{ error|escape }} field is required.</strong>
        </li>
      </ul>
    {% endfor %}
  {% endif %}

  <form action="" name="add_task" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_full_name" name="full_name">Nombre completo</label>
        <input type="text" class="form-control" id="id_full_name" name="full_name" required placeholder="Introduzca su nombre completo"
          value="{% if form.full_name.value %}{{ form.full_name.value }}{% endif %}">
      </div>
      <div class="form-group">
        <label for="id_email" name="email">Email</label>
        <input type="email" class="form-control" id="id_email" name="email" required placeholder="algo@gmail.com" value="{{ user.email }}">
      </div>
      <div class="form-group">
        <label for="id_name" name="name">Título</label>
        <input type="text" class="form-control" id="id_name" name="name" required placeholder="Título de su obra"
          value="{% if form_book.name.value %}{{ form_book.name.value }}{% endif %}">
      </div>
      <div class="form-group">
        <label for="id_note">Descripción</label>
        <textarea class="form-control" id="id_note" name="description" rows="5" required
          aria-describedby="inputNoteHelp">{% if form_book.description.value %}{{ form_book.description.value }}{% endif %}</textarea>
        <small id="inputNoteHelp" class="form_book-text text-muted">
          Añada la sinopsis del libro o cualquier comentario que considere relevante.
        </small>
      </div>
      
      <div class="form-task-type">
        <label for="thematic">Temática</label>
        {{form_book.thematic}}
      </div>

      <div class="form-task-type">
        <label for="file">Adjunta tu libro</label>
          <div class="input-group mb-3">
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="attachment_file_input" name="attachment_file_input" />
              <label class="custom-file-label" for="attachment_file_input">Seleccione un archivo...</label>
            </div>
          </div>
      </div>

            
      <div class="form-task-type">
        <input type="checkbox" name="policy" value="Accepted" required>
        <label style="display: inline;" for="policy"> Al enviar este formulario acepto la <a href="/">Política de privacidad</a> y las <a href="/">Condiciones de uso</a> </label><br><br>
      </div>
  
      <input type="hidden" id="id_priority" name="priority" value="50">
      <p><input type="submit" class="btn btn-primary" name="add_task" value="Enviar"></p>
  </form>

{% endblock %}


{% block extra_js %}
  {# Support file attachment uploader #}
  <script>
    $('#attachment_file_input').on('change',function(){
      // Get the file name and remove browser-added "fakepath."
      // Then replace the "Choose a file" label.
      var fileName = $(this).val().replace('C:\\fakepath\\', " ");
      $(this).next('.custom-file-label').html(fileName);
    })
  </script>
{% endblock extra_js %}

todo/templates/todo/book_edit.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Publicacion libro{% endblock %}

{% block content %}

  <h3 class="bar-text">FORMULARIO DE EDICIÓN</h3>
  <hr>

  {% if form.errors %}
    {% for error in form.errors %}
      <ul class="errorlist">
        <li>
          <strong>El campo {{ error|escape }} debe rellenarse obligatoriamente.</strong>
        </li>
      </ul>
    {% endfor %}
  {% endif %}

  <form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="mt-3">
      <div class="form-group">
        <label for="id_title" name="title">TÍTULO DEL LIBRO</label>
        <input required type="text" class="form-control" id="id_title" name="title" placeholder="{{ book.title }}"
          value="{{ book.title }}">
      </div>
    </div>

    <div class="mt-3">
      <div class="form-group">
        <label for="id_author" name="author">AUTOR/ES</label>
        <input type="text" class="form-control" id="id_author" name="author" placeholder="{{ book.author_text }}"
          value="{{ book.author_text }}">
      </div>
    </div>

    <div class="form-group">
      <label for="id_note">SINOPSIS</label>
      <textarea class="form-control" id="id_note" name="description" rows="7"
        aria-describedby="inputNoteHelp">{% if book.book.description %}{{ book.book.description }}{% endif %}</textarea>
      <small id="inputNoteHelp" class="form-text text-muted">
        Esta sinopsis será la mostrada a los lectores. 
      </small>
    </div>

    <div class="mt-3">
      <div class="form-group">
        <label for="id_image" name="image">¿DESEA ADJUNTAR/MODIFICAR LA IMÁGEN?</label>
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="attachment_image_input" name="attachment_image_input" accept="image/*"/>
          <label class="custom-file-label" for="attachment_image_input">Escoja una imágen...</label>
        </div>
      </div>
    </div>

    <div class="mt-3">
      <div class="form-group">
        <label for="id_file">ADJUNTE LA VERSIÓN FINAL EN FORMATO PDF</label>
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="attachment_file_input" name="attachment_file_input" accept=".pdf"/>
          <label class="custom-file-label" for="attachment_file_input">Seleccione la versión final maquetada del libro...</label>
        </div>
      </div>
    </div>

    <br/>
    <input id="submitBtn" type="button" class="btn btn-primary pull-right" name="publish" onclick="submit(this.form)" value="CONFIRMAR CAMBIOS">
    <br/>
    <br/>
    <br/>
  </form>

{% endblock %}

{% block extra_js %}
  {# Support file attachment uploader #}
  <script>
    function submit(formToPost) {
      if (!formToPost.reportValidity()){
        return;
      }
      if(confirm("¿Confirma que todos los campos són correctos?")){
        formToPost.submit();
      }
    }
    $('#attachment_file_input').on('change',function(){
      // Get the file name and remove browser-added "fakepath."
      // Then replace the "Choose a file" label.
      var fileName = $(this).val().replace('C:\\fakepath\\', " ");
      $(this).next('.custom-file-label').html(fileName);
    })
    $('#attachment_image_input').on('change',function(){
      // Get the file name and remove browser-added "fakepath."
      // Then replace the "Choose a file" label.
      var fileName = $(this).val().replace('C:\\fakepath\\', " ");
      $(this).next('.custom-file-label').html(fileName);
    })
  </script>
{% endblock extra_js %}

todo/templates/todo/books_management.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Books management {% endblock %}

{% block content %}

<h1 style="font-family: 'BebasNeueRegular'; margin-top: 40px;">Gestión de libros</h1>

<table class="table" id="tasktable">
  <tr class="nodrop">
    <th>Título</th>
    <th>Autor</th>
    <th></th>
  </tr>
  
  {% for book in books %} 
  <tr>
    <td>
      <a style="color:blue" href="{% url 'todo:book_statistics' book.book.pk %}" >
          {{ book.title }}
      </a>
    </td>
    <td>
          {{ book.author_text }}
    </td>
    <td>
    {% if book in active_books %}
      <form method="post" action="{% url "todo:deactivate_book" %}" role="form" class="d-inline">
        {% csrf_token %}
        <input type="hidden" name="reasons" value=""/>
        <input type="hidden" name="deactivate-book" value="{{ book.pk }}"/>
        <button type="submit" class="btn btn-danger btn-sm"><b>DESACTIVAR</b></button>
      </form>
    {% elif book in unactive_books %} 
      <form method="post" action="{% url "todo:activate_book" %}" role="form" class="d-inline">
        {% csrf_token %}
        <input type="hidden" name="reasons" value=""/>
        <input type="hidden" name="activate-book" value="{{ book.pk }}"/>
        <button type="submit" class="btn btn-success btn-sm"><b>ACTIVAR</b></button>
      </form>
    {% endif %}
    <form style="display: inline-block" action="{% url 'todo:book_edit' book.id %}" method="get">
      <button class="btn btn-secondary btn-sm"><b>EDITAR</b></button>
    </form>
    </td>
  </tr>
  {% endfor %} 
  </table>
  
<script>
  document.getElementById("management-books").style.borderBottom = "4px solid rgb(133, 5, 5)";
</script>

{% endblock %}

todo/templates/todo/cancel_subscription.html
{% extends "todo/main.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Cancelar subscripción{% endblock %}

{% block content %}

<h3 class="bar-text">¿QUIERES CANCELAR LA SUBSCRIPCIÓN?</h3>
<hr>
<h5>Haz clic en Cancelar subscripción a continuación para cancelar tu suscripción.</h5>
<ul>
    <li>La cancelación se hará efectiva al finalizar el período de facturación actual.</li>
</ul>
<form action="{% url 'todo:cancel_subscription' %}" method="POST">
    {% csrf_token %}
    <input onclick="return confirm('¿Está seguro/a que desea cancelar la subscripción?');" type="submit" name="cancel" value="CANCELAR SUBSCRIPCIÓN" class="btn btn-danger">
    <input type="submit" class="btn btn-secondary" name="back" value="VOLVER"></input>
</form>

{% endblock %}

todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Tasks Lists{% endblock %}

{% block content %}
  <h1 style="font-family: 'BebasNeueRegular'; margin-top: 40px;">Peticiones de edición</h1>

  <p>Hay {{ list_count }} propuesta{{ list_count|pluralize }} pendiente{{ list_count|pluralize }}</p>

  {% regroup lists by group as section_list %}
  {% for group in section_list %}
    <!-- <h3>Group: {{ group.grouper }}</h3> -->
    <ul class="list-group mb-4">
      {% for task in group.list %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if assigned_to == None %}
          <a href="{% url 'todo:book_assign' task.id %}">{{ task.name }}</a>
        {% else %}
          <a href="{% url 'todo:list_detail' task.id task.slug %}">{{ task.name }}</a>
          <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
        {% endif %}
      </li>
      {% endfor %}
    </ul>
  {% endfor %}

  <script>
    document.getElementById("peticiones").style.borderBottom = "4px solid rgb(133, 5, 5)";
  </script>
{% endblock %}

todo/templates/todo/users_management.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Users management {% endblock %}

{% block content %}

<h1 style="font-family: 'BebasNeueRegular'; margin-top: 40px;">Gestión de usuarios</h1>
{% for section, list_slug in section_list.items %}
    <ul class="list-group mb-4">
      <li id="{{ section }}" class="list-group-item d-flex justify-content-between align-items-center">
        <a style="color:blue;" href="{% url 'todo:users_detail' list_slug %}">{{ section }}</a>
      </li>
    </ul>
{% endfor %}
  
<script>
  document.getElementById("management-users").style.borderBottom = "4px solid rgb(133, 5, 5)";
</script>

{% endblock %}